import { Bot, Database, Globe, Layers, LockKeyhole, SlidersHorizontal, FileDown } from "lucide-react";

export const settingsGroups = [
  { id: "llm", en: "Language model", zh: "语言模型", icon: Bot, description: ["Configure the models used for answers, topic reports and paper briefings. Set the URL, key and model together, or leave all three empty to use the local implementation. The briefing model is optional and falls back to the main model when empty.", "用于论文问答、话题报告和论文速览。接口地址、密钥和模型名称需一起配置；三项均留空时使用本地实现。速览模型为可选，留空时沿用主模型。"] },
  { id: "embedding", en: "Embeddings", zh: "嵌入模型", icon: Layers, description: ["Configure semantic retrieval. Changing the model or dimensions requires re-indexing existing papers; until then, retrieval safely falls back within each paper.", "用于语义检索。更换模型或维度后，已有论文需重新建立索引；在此之前会在当前论文内降级检索。"] },
  { id: "research", en: "Topic exploration", zh: "话题探索", icon: Globe, description: ["Control arXiv search, retries and report context. Intervals must be at least 3 seconds; the total timeout limits the entire search.", "管理 arXiv 检索、重试和报告上下文。请求间隔至少 3 秒，总超时限制整次搜索的等待时间。"] },
  { id: "ingestion", en: "Paper reading", zh: "论文阅读", icon: FileDown, description: ["Set download limits, ingestion retries and the maximum question length.", "设置下载限制、论文摄取重试次数和提问长度。"] },
  { id: "storage", en: "Storage & services", zh: "存储与服务", icon: Database, description: ["Local storage and database retrieval work without additional services. Changing a database or storage path does not migrate existing data.", "本地存储和数据库检索无需额外服务。更改数据库或存储目录不会迁移已有数据。"] },
  { id: "security", en: "Security", zh: "安全与访问", icon: LockKeyhole, description: ["Manage authentication and request limits. When enabled, the API token is required; an empty internal token inherits it on startup.", "管理鉴权和请求频率。启用鉴权后必须配置 API Token；内部代理 Token 留空时会在启动时沿用它。"] },
  { id: "runtime", en: "General & network", zh: "通用与网络", icon: SlidersHorizontal, description: ["Set addresses and ports together with their origins and proxy URL. The settings editor is available only when both services bind to localhost or loopback addresses.", "修改端口时请同步检查来源地址和内部代理地址。设置编辑器仅在前后端均绑定 localhost 或回环地址时可用。"] },
] as const;

// Values are supplied by the server. This catalog contains labels only, never configuration.
export const fieldLabels: Record<string, [string, string]> = {
  APP_NAME: ["Application name", "应用名称"],
  ENVIRONMENT: ["Environment", "运行环境"],
  LOG_LEVEL: ["Log level", "日志级别"],
  API_HOST: ["API bind address", "API 监听地址"],
  API_PORT: ["API port", "API 端口"],
  WEB_HOST: ["Web bind address", "前端监听地址"],
  WEB_PORT: ["Web port", "前端端口"],
  WEB_ORIGIN: ["Web origin", "前端来源地址"],
  CORS_ORIGINS: ["Allowed origins", "允许的跨域来源"],
  AUTH_REQUIRED: ["Require authentication", "启用鉴权"],
  API_BEARER_TOKEN: ["API access token", "API 访问 Token"],
  RATE_LIMIT_REQUESTS: ["Requests per window", "每个窗口的请求上限"],
  RATE_LIMIT_WINDOW_SECONDS: ["Rate limit window · seconds", "限流窗口 · 秒"],
  DATABASE_URL: ["Database connection", "数据库连接地址"],
  REDIS_URL: ["Redis connection", "Redis 连接地址"],
  QUEUE_MODE: ["Task queue", "任务队列模式"],
  AUTO_CREATE_SCHEMA: ["Create schema automatically", "自动创建数据库结构"],
  STORAGE_BACKEND: ["Object storage", "对象存储方式"],
  LOCAL_STORAGE_PATH: ["Local storage directory", "本地文件存储目录"],
  RETRIEVAL_BACKEND: ["Retrieval backend", "检索后端"],
  PAPER_RETENTION_DAYS: ["Paper retention · days", "论文保留时间 · 天"],
  WORKER_METRICS_PORT: ["Worker metrics port · 0 disables", "Worker 指标端口 · 0 为关闭"],
  S3_ENDPOINT_URL: ["S3 endpoint", "S3 服务地址"],
  S3_ACCESS_KEY_ID: ["S3 access key ID", "S3 访问密钥 ID"],
  S3_SECRET_ACCESS_KEY: ["S3 secret access key", "S3 访问密钥"],
  S3_BUCKET: ["S3 bucket", "S3 存储桶"],
  S3_REGION: ["S3 region", "S3 区域"],
  QDRANT_URL: ["Qdrant endpoint", "Qdrant 服务地址"],
  QDRANT_API_KEY: ["Qdrant API key", "Qdrant API 密钥"],
  QDRANT_COLLECTION: ["Qdrant collection", "Qdrant 集合名称"],
  LLM_BASE_URL: ["API base URL", "接口地址"],
  LLM_API_KEY: ["API key", "API 密钥"],
  LLM_MODEL: ["Model name", "模型名称"],
  SUMMARY_LLM_MODEL: ["Briefing model name (optional)", "速览模型名称（可选）"],
  LLM_TEMPERATURE: ["Temperature", "生成温度"],
  LLM_MAX_OUTPUT_TOKENS: ["Maximum output tokens", "最大输出 Token 数"],
  MAX_CONTEXT_CHARACTERS: ["Answer context · characters", "问答上下文 · 字符"],
  SUMMARY_MAX_CONTEXT_CHARACTERS: ["Briefing context · characters", "速览上下文 · 字符"],
  EMBEDDING_BASE_URL: ["API base URL", "接口地址"],
  EMBEDDING_API_KEY: ["API key", "API 密钥"],
  EMBEDDING_MODEL: ["Model name", "模型名称"],
  EMBEDDING_DIMENSION: ["Embedding dimensions", "向量维度"],
  ARXIV_USER_AGENT: ["arXiv user agent", "arXiv 请求标识"],
  ARXIV_SEARCH_MIN_INTERVAL_SECONDS: ["Minimum request interval · seconds", "最短请求间隔 · 秒"],
  ARXIV_SEARCH_MAX_ATTEMPTS: ["Maximum search attempts", "搜索最大尝试次数"],
  ARXIV_SEARCH_ATTEMPT_TIMEOUT_SECONDS: ["Timeout per attempt · seconds", "每次尝试超时 · 秒"],
  ARXIV_SEARCH_TOTAL_TIMEOUT_SECONDS: ["Total search timeout · seconds", "搜索总超时 · 秒"],
  RESEARCH_CACHE_TTL_SECONDS: ["Search cache lifetime · seconds", "搜索缓存有效期 · 秒"],
  RESEARCH_MAX_CONTEXT_CHARACTERS: ["Report context · characters", "报告上下文 · 字符"],
  MAX_PDF_BYTES: ["Maximum PDF size · bytes", "PDF 大小上限 · 字节"],
  MAX_PDF_PAGES: ["Maximum PDF pages", "PDF 页数上限"],
  INGESTION_MAX_ATTEMPTS: ["Maximum ingestion attempts", "摄取最大尝试次数"],
  DOWNLOAD_CONNECT_TIMEOUT_SECONDS: ["Connection timeout · seconds", "下载连接超时 · 秒"],
  DOWNLOAD_READ_TIMEOUT_SECONDS: ["Read timeout · seconds", "下载读取超时 · 秒"],
  MAX_QUERY_CHARACTERS: ["Question length · characters", "提问长度上限 · 字符"],
  API_INTERNAL_URL: ["Internal API URL", "内部 API 代理地址"],
  API_INTERNAL_BEARER_TOKEN: ["Internal API token", "内部 API 代理 Token"],
};
