"""initial_schema

Revision ID: 0f1f61f7b6d7
Revises:
Create Date: 2026-08-20 22:05:24.372549
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "0f1f61f7b6d7"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "papers",
        sa.Column("owner_id", sa.String(length=128), nullable=False),
        sa.Column("arxiv_id", sa.String(length=64), nullable=False),
        sa.Column("base_arxiv_id", sa.String(length=64), nullable=False),
        sa.Column("arxiv_version", sa.Integer(), nullable=True),
        sa.Column("abstract_url", sa.String(length=512), nullable=False),
        sa.Column("pdf_url", sa.String(length=512), nullable=False),
        sa.Column("title", sa.String(length=1000), nullable=True),
        sa.Column("authors", sa.JSON(), nullable=False),
        sa.Column("abstract", sa.Text(), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "QUEUED",
                "DOWNLOADING",
                "PARSING",
                "INDEXING",
                "READY",
                "FAILED",
                name="paperstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("error_code", sa.String(length=128), nullable=True),
        sa.Column("error_message", sa.String(length=1000), nullable=True),
        sa.Column("pdf_object_key", sa.String(length=512), nullable=True),
        sa.Column("markdown_object_key", sa.String(length=512), nullable=True),
        sa.Column("content_sha256", sa.String(length=64), nullable=True),
        sa.Column("parser_version", sa.String(length=64), nullable=True),
        sa.Column("retrieval_namespace", sa.String(length=128), nullable=True),
        sa.Column("indexed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ready_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_papers")),
        sa.UniqueConstraint("owner_id", "arxiv_id", name="uq_papers_owner_arxiv"),
        sa.UniqueConstraint("retrieval_namespace", name=op.f("uq_papers_retrieval_namespace")),
    )
    op.create_index(op.f("ix_papers_owner_id"), "papers", ["owner_id"], unique=False)
    op.create_index("ix_papers_owner_status", "papers", ["owner_id", "status"], unique=False)
    op.create_index(op.f("ix_papers_status"), "papers", ["status"], unique=False)
    op.create_table(
        "conversations",
        sa.Column("paper_id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.String(length=128), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["paper_id"],
            ["papers.id"],
            name=op.f("fk_conversations_paper_id_papers"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_conversations")),
    )
    op.create_index(op.f("ix_conversations_owner_id"), "conversations", ["owner_id"], unique=False)
    op.create_index(
        "ix_conversations_owner_paper", "conversations", ["owner_id", "paper_id"], unique=False
    )
    op.create_index(op.f("ix_conversations_paper_id"), "conversations", ["paper_id"], unique=False)
    op.create_table(
        "ingestion_jobs",
        sa.Column("paper_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "QUEUED",
                "RUNNING",
                "RETRYING",
                "SUCCEEDED",
                "FAILED",
                name="jobstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "stage",
            sa.Enum(
                "QUEUED",
                "METADATA",
                "DOWNLOAD",
                "PARSE",
                "STORE",
                "INDEX",
                "COMPLETE",
                name="jobstage",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("progress", sa.Integer(), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("queue_job_id", sa.String(length=128), nullable=True),
        sa.Column("error_code", sa.String(length=128), nullable=True),
        sa.Column("error_message", sa.String(length=1000), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["paper_id"],
            ["papers.id"],
            name=op.f("fk_ingestion_jobs_paper_id_papers"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingestion_jobs")),
        sa.UniqueConstraint("queue_job_id", name=op.f("uq_ingestion_jobs_queue_job_id")),
    )
    op.create_index(
        op.f("ix_ingestion_jobs_paper_id"), "ingestion_jobs", ["paper_id"], unique=False
    )
    op.create_index(
        "ix_jobs_paper_created", "ingestion_jobs", ["paper_id", "created_at"], unique=False
    )
    op.create_table(
        "paper_chunks",
        sa.Column("paper_id", sa.Uuid(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("page_number", sa.Integer(), nullable=True),
        sa.Column("section", sa.String(length=500), nullable=True),
        sa.Column("token_count", sa.Integer(), nullable=False),
        sa.Column("content_sha256", sa.String(length=64), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["paper_id"],
            ["papers.id"],
            name=op.f("fk_paper_chunks_paper_id_papers"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_paper_chunks")),
        sa.UniqueConstraint("paper_id", "ordinal", name="uq_chunks_paper_ordinal"),
    )
    op.create_index(
        "ix_chunks_paper_page", "paper_chunks", ["paper_id", "page_number"], unique=False
    )
    op.create_index(op.f("ix_paper_chunks_paper_id"), "paper_chunks", ["paper_id"], unique=False)
    op.create_table(
        "chat_messages",
        sa.Column("conversation_id", sa.Uuid(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("USER", "ASSISTANT", name="messagerole", native_enum=False, length=16),
            nullable=False,
        ),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("citations", sa.JSON(), nullable=False),
        sa.Column("latency_ms", sa.Float(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_chat_messages_conversation_id_conversations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chat_messages")),
    )
    op.create_index(
        op.f("ix_chat_messages_conversation_id"), "chat_messages", ["conversation_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_chat_messages_conversation_id"), table_name="chat_messages")
    op.drop_table("chat_messages")
    op.drop_index(op.f("ix_paper_chunks_paper_id"), table_name="paper_chunks")
    op.drop_index("ix_chunks_paper_page", table_name="paper_chunks")
    op.drop_table("paper_chunks")
    op.drop_index("ix_jobs_paper_created", table_name="ingestion_jobs")
    op.drop_index(op.f("ix_ingestion_jobs_paper_id"), table_name="ingestion_jobs")
    op.drop_table("ingestion_jobs")
    op.drop_index(op.f("ix_conversations_paper_id"), table_name="conversations")
    op.drop_index("ix_conversations_owner_paper", table_name="conversations")
    op.drop_index(op.f("ix_conversations_owner_id"), table_name="conversations")
    op.drop_table("conversations")
    op.drop_index(op.f("ix_papers_status"), table_name="papers")
    op.drop_index("ix_papers_owner_status", table_name="papers")
    op.drop_index(op.f("ix_papers_owner_id"), table_name="papers")
    op.drop_table("papers")
    # ### end Alembic commands ###
